### PR TITLE
Fixes #11 and #28

### LINKED ISSUE #11: Use Kotlin DSL for Kotlin examples
I have a working `build.gradle.kts` written in Kotlin DSL for example-jdbc-kotlin. If you like, I can submit it in a PR.

Of course, if we switch from Groovy to Kotlin for this example, we should probably do it for all Kotlin examples across the Micronaut ecosystem. If you're interested in changing them, I can take a look at the others  and probably submit PRs for those as well.

### PR DESCRIPTION
**Pull request by kensiprell**
I submitted a PR last week (10: 'Cannot write a read-only property' exception in example-jdbc-kotlin), but I screwed my fork between that commit and the one migrating build.gradle to kotin DSL. I decided to start over with a clean fork before I unnecessarily cluttered up the code base.

I apologize for the confusion and will try to be more careful in the future.

### CODE REVIEW

**Comment by kensiprell** [comment]
P.S. It's been awhile since I've made contributions to other repos, so I'm git rusty. In the future I'll push my changes for a single feature or bug to a new branch on my fork and submit separate PRs from those. I appreciate your patience!

If you like, I can redo this PR as two separate ones. I'd also welcome any other tips or suggestions.

**Comment by graemerocher** [comment]
No worries, for the change to the Kotlin example, I need to figure out why that is not working first. Thanks

**Comment by kensiprell** [comment]
I think I might have figured out what's going on with the Kotlin data class. I set a breakpoint at https://github.com/micronaut-projects/micronaut-predator/blob/dc605a152a3bc3df7a2794f75b3097f38a491d71/examples/example-jdbc-kotlin/src/main/kotlin/example/domain/NameDTO.kt#L6 after substituting `var` for `val` and then made a call to http://localhost:8080/pets/.

Just pressing the resume program button would show the object (NameDTO) being instantiated and the next resume would show a `set` being called on the same object. As I'm sure you know a `val` in a Kotlin data class constructor results in an immutable property.

Tonight after using the debugger to step into what's going on, here's what I think is happening:

The `@Introspected` annotation is instantiating  the object here

```
public Object instantiateInternal(Object[] var1) {
     return new NameDTO((String)var1[0]);
 }
```

and then Kotlin attempts to generate the same class only to fail because the object already exists with an immutable `name` property.

**Comment by graemerocher** [comment]
Going to merge this for now and investigate the issue soon

**Pull request merged**
